"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import sys
import typing

import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message

import temporalio.api.common.v1.message_pb2
import temporalio.api.enums.v1.update_pb2
import temporalio.api.failure.v1.message_pb2

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class WaitPolicy(google.protobuf.message.Message):
    """Specifies client's intent to wait for Update results."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LIFECYCLE_STAGE_FIELD_NUMBER: builtins.int
    lifecycle_stage: temporalio.api.enums.v1.update_pb2.UpdateWorkflowExecutionLifecycleStage.ValueType
    """Indicates the Update lifecycle stage that the Update must reach before
    API call is returned.
    NOTE: This field works together with API call timeout which is limited by
    server timeout (maximum wait time). If server timeout is expired before
    user specified timeout, API call returns even if specified stage is not reached.
    """
    def __init__(
        self,
        *,
        lifecycle_stage: temporalio.api.enums.v1.update_pb2.UpdateWorkflowExecutionLifecycleStage.ValueType = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["lifecycle_stage", b"lifecycle_stage"]
    ) -> None: ...

Global___WaitPolicy: typing_extensions.TypeAlias = WaitPolicy

@typing.final
class UpdateRef(google.protobuf.message.Message):
    """The data needed by a client to refer to a previously invoked Workflow Update."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WORKFLOW_EXECUTION_FIELD_NUMBER: builtins.int
    UPDATE_ID_FIELD_NUMBER: builtins.int
    update_id: builtins.str
    @property
    def workflow_execution(
        self,
    ) -> temporalio.api.common.v1.message_pb2.WorkflowExecution: ...
    def __init__(
        self,
        *,
        workflow_execution: temporalio.api.common.v1.message_pb2.WorkflowExecution
        | None = ...,
        update_id: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["workflow_execution", b"workflow_execution"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "update_id", b"update_id", "workflow_execution", b"workflow_execution"
        ],
    ) -> None: ...

Global___UpdateRef: typing_extensions.TypeAlias = UpdateRef

@typing.final
class Outcome(google.protobuf.message.Message):
    """The outcome of a Workflow Update: success or failure."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    FAILURE_FIELD_NUMBER: builtins.int
    @property
    def success(self) -> temporalio.api.common.v1.message_pb2.Payloads: ...
    @property
    def failure(self) -> temporalio.api.failure.v1.message_pb2.Failure: ...
    def __init__(
        self,
        *,
        success: temporalio.api.common.v1.message_pb2.Payloads | None = ...,
        failure: temporalio.api.failure.v1.message_pb2.Failure | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "failure", b"failure", "success", b"success", "value", b"value"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "failure", b"failure", "success", b"success", "value", b"value"
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["value", b"value"]
    ) -> typing.Literal["success", "failure"] | None: ...

Global___Outcome: typing_extensions.TypeAlias = Outcome

@typing.final
class Meta(google.protobuf.message.Message):
    """Metadata about a Workflow Update."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UPDATE_ID_FIELD_NUMBER: builtins.int
    IDENTITY_FIELD_NUMBER: builtins.int
    update_id: builtins.str
    """An ID with workflow-scoped uniqueness for this Update."""
    identity: builtins.str
    """A string identifying the agent that requested this Update."""
    def __init__(
        self,
        *,
        update_id: builtins.str = ...,
        identity: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal["identity", b"identity", "update_id", b"update_id"],
    ) -> None: ...

Global___Meta: typing_extensions.TypeAlias = Meta

@typing.final
class Input(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of the Update handler to invoke on the target Workflow."""
    @property
    def header(self) -> temporalio.api.common.v1.message_pb2.Header:
        """Headers that are passed with the Update from the requesting entity.
        These can include things like auth or tracing tokens.
        """

    @property
    def args(self) -> temporalio.api.common.v1.message_pb2.Payloads:
        """The arguments to pass to the named Update handler."""

    def __init__(
        self,
        *,
        header: temporalio.api.common.v1.message_pb2.Header | None = ...,
        name: builtins.str = ...,
        args: temporalio.api.common.v1.message_pb2.Payloads | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["args", b"args", "header", b"header"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "args", b"args", "header", b"header", "name", b"name"
        ],
    ) -> None: ...

Global___Input: typing_extensions.TypeAlias = Input

@typing.final
class Request(google.protobuf.message.Message):
    """The client request that triggers a Workflow Update."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    INPUT_FIELD_NUMBER: builtins.int
    REQUEST_ID_FIELD_NUMBER: builtins.int
    COMPLETION_CALLBACKS_FIELD_NUMBER: builtins.int
    LINKS_FIELD_NUMBER: builtins.int
    request_id: builtins.str
    """The request ID of the request."""
    @property
    def meta(self) -> Global___Meta: ...
    @property
    def input(self) -> Global___Input: ...
    @property
    def completion_callbacks(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        temporalio.api.common.v1.message_pb2.Callback
    ]:
        """Callbacks to be called by the server when this update reaches a terminal state."""

    @property
    def links(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        temporalio.api.common.v1.message_pb2.Link
    ]:
        """Links to be associated with this update."""

    def __init__(
        self,
        *,
        meta: Global___Meta | None = ...,
        input: Global___Input | None = ...,
        request_id: builtins.str = ...,
        completion_callbacks: collections.abc.Iterable[
            temporalio.api.common.v1.message_pb2.Callback
        ]
        | None = ...,
        links: collections.abc.Iterable[temporalio.api.common.v1.message_pb2.Link]
        | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["input", b"input", "meta", b"meta"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "completion_callbacks",
            b"completion_callbacks",
            "input",
            b"input",
            "links",
            b"links",
            "meta",
            b"meta",
            "request_id",
            b"request_id",
        ],
    ) -> None: ...

Global___Request: typing_extensions.TypeAlias = Request

@typing.final
class Rejection(google.protobuf.message.Message):
    """An Update protocol message indicating that a Workflow Update has been rejected."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REJECTED_REQUEST_MESSAGE_ID_FIELD_NUMBER: builtins.int
    REJECTED_REQUEST_SEQUENCING_EVENT_ID_FIELD_NUMBER: builtins.int
    REJECTED_REQUEST_FIELD_NUMBER: builtins.int
    FAILURE_FIELD_NUMBER: builtins.int
    rejected_request_message_id: builtins.str
    rejected_request_sequencing_event_id: builtins.int
    @property
    def rejected_request(self) -> Global___Request: ...
    @property
    def failure(self) -> temporalio.api.failure.v1.message_pb2.Failure: ...
    def __init__(
        self,
        *,
        rejected_request_message_id: builtins.str = ...,
        rejected_request_sequencing_event_id: builtins.int = ...,
        rejected_request: Global___Request | None = ...,
        failure: temporalio.api.failure.v1.message_pb2.Failure | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "failure", b"failure", "rejected_request", b"rejected_request"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "failure",
            b"failure",
            "rejected_request",
            b"rejected_request",
            "rejected_request_message_id",
            b"rejected_request_message_id",
            "rejected_request_sequencing_event_id",
            b"rejected_request_sequencing_event_id",
        ],
    ) -> None: ...

Global___Rejection: typing_extensions.TypeAlias = Rejection

@typing.final
class Acceptance(google.protobuf.message.Message):
    """An Update protocol message indicating that a Workflow Update has
    been accepted (i.e. passed the worker-side validation phase).
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCEPTED_REQUEST_MESSAGE_ID_FIELD_NUMBER: builtins.int
    ACCEPTED_REQUEST_SEQUENCING_EVENT_ID_FIELD_NUMBER: builtins.int
    ACCEPTED_REQUEST_FIELD_NUMBER: builtins.int
    accepted_request_message_id: builtins.str
    accepted_request_sequencing_event_id: builtins.int
    @property
    def accepted_request(self) -> Global___Request: ...
    def __init__(
        self,
        *,
        accepted_request_message_id: builtins.str = ...,
        accepted_request_sequencing_event_id: builtins.int = ...,
        accepted_request: Global___Request | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["accepted_request", b"accepted_request"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "accepted_request",
            b"accepted_request",
            "accepted_request_message_id",
            b"accepted_request_message_id",
            "accepted_request_sequencing_event_id",
            b"accepted_request_sequencing_event_id",
        ],
    ) -> None: ...

Global___Acceptance: typing_extensions.TypeAlias = Acceptance

@typing.final
class Response(google.protobuf.message.Message):
    """An Update protocol message indicating that a Workflow Update has
    completed with the contained outcome.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    META_FIELD_NUMBER: builtins.int
    OUTCOME_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> Global___Meta: ...
    @property
    def outcome(self) -> Global___Outcome: ...
    def __init__(
        self,
        *,
        meta: Global___Meta | None = ...,
        outcome: Global___Outcome | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["meta", b"meta", "outcome", b"outcome"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["meta", b"meta", "outcome", b"outcome"]
    ) -> None: ...

Global___Response: typing_extensions.TypeAlias = Response
