# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/sdk/v1/worker_config.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    "",
    "temporal/api/sdk/v1/worker_config.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n'temporal/api/sdk/v1/worker_config.proto\x12\x13temporal.api.sdk.v1\"\x89\x03\n\x0cWorkerConfig\x12\x1b\n\x13workflow_cache_size\x18\x01 \x01(\x05\x12X\n\x16simple_poller_behavior\x18\x02 \x01(\x0b\x32\x36.temporal.api.sdk.v1.WorkerConfig.SimplePollerBehaviorH\x00\x12\x62\n\x1b\x61utoscaling_poller_behavior\x18\x03 \x01(\x0b\x32;.temporal.api.sdk.v1.WorkerConfig.AutoscalingPollerBehaviorH\x00\x1a+\n\x14SimplePollerBehavior\x12\x13\n\x0bmax_pollers\x18\x01 \x01(\x05\x1a^\n\x19\x41utoscalingPollerBehavior\x12\x13\n\x0bmin_pollers\x18\x01 \x01(\x05\x12\x13\n\x0bmax_pollers\x18\x02 \x01(\x05\x12\x17\n\x0finitial_pollers\x18\x03 \x01(\x05\x42\x11\n\x0fpoller_behaviorB\x7f\n\x16io.temporal.api.sdk.v1B\x11WorkerConfigProtoP\x01Z\x1dgo.temporal.io/api/sdk/v1;sdk\xaa\x02\x15Temporalio.Api.Sdk.V1\xea\x02\x18Temporalio::Api::Sdk::V1b\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "temporal.api.sdk.v1.worker_config_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n\026io.temporal.api.sdk.v1B\021WorkerConfigProtoP\001Z\035go.temporal.io/api/sdk/v1;sdk\252\002\025Temporalio.Api.Sdk.V1\352\002\030Temporalio::Api::Sdk::V1"
    _globals["_WORKERCONFIG"]._serialized_start = 65
    _globals["_WORKERCONFIG"]._serialized_end = 458
    _globals["_WORKERCONFIG_SIMPLEPOLLERBEHAVIOR"]._serialized_start = 300
    _globals["_WORKERCONFIG_SIMPLEPOLLERBEHAVIOR"]._serialized_end = 343
    _globals["_WORKERCONFIG_AUTOSCALINGPOLLERBEHAVIOR"]._serialized_start = 345
    _globals["_WORKERCONFIG_AUTOSCALINGPOLLERBEHAVIOR"]._serialized_end = 439
# @@protoc_insertion_point(module_scope)
