"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import sys
import typing

import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.empty_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2

import temporalio.api.enums.v1.common_pb2
import temporalio.api.enums.v1.event_type_pb2
import temporalio.api.enums.v1.reset_pb2

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DataBlob(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENCODING_TYPE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    encoding_type: temporalio.api.enums.v1.common_pb2.EncodingType.ValueType
    data: builtins.bytes
    def __init__(
        self,
        *,
        encoding_type: temporalio.api.enums.v1.common_pb2.EncodingType.ValueType = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal["data", b"data", "encoding_type", b"encoding_type"],
    ) -> None: ...

Global___DataBlob: typing_extensions.TypeAlias = DataBlob

@typing.final
class Payloads(google.protobuf.message.Message):
    """See `Payload`"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYLOADS_FIELD_NUMBER: builtins.int
    @property
    def payloads(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___Payload
    ]: ...
    def __init__(
        self,
        *,
        payloads: collections.abc.Iterable[Global___Payload] | None = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["payloads", b"payloads"]
    ) -> None: ...

Global___Payloads: typing_extensions.TypeAlias = Payloads

@typing.final
class Payload(google.protobuf.message.Message):
    """Represents some binary (byte array) data (ex: activity input parameters or workflow result) with
    metadata which describes this binary data (format, encoding, encryption, etc). Serialization
    of the data may be user-defined.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.bytes
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.bytes = ...,
        ) -> None: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    @typing.final
    class ExternalPayloadDetails(google.protobuf.message.Message):
        """Describes an externally stored object referenced by this payload."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SIZE_BYTES_FIELD_NUMBER: builtins.int
        size_bytes: builtins.int
        """Size in bytes of the externally stored payload"""
        def __init__(
            self,
            *,
            size_bytes: builtins.int = ...,
        ) -> None: ...
        def ClearField(
            self, field_name: typing.Literal["size_bytes", b"size_bytes"]
        ) -> None: ...

    METADATA_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    EXTERNAL_PAYLOADS_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    @property
    def metadata(
        self,
    ) -> google.protobuf.internal.containers.ScalarMap[
        builtins.str, builtins.bytes
    ]: ...
    @property
    def external_payloads(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___Payload.ExternalPayloadDetails
    ]:
        """Details about externally stored payloads associated with this payload."""

    def __init__(
        self,
        *,
        metadata: collections.abc.Mapping[builtins.str, builtins.bytes] | None = ...,
        data: builtins.bytes = ...,
        external_payloads: collections.abc.Iterable[
            Global___Payload.ExternalPayloadDetails
        ]
        | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "data",
            b"data",
            "external_payloads",
            b"external_payloads",
            "metadata",
            b"metadata",
        ],
    ) -> None: ...

Global___Payload: typing_extensions.TypeAlias = Payload

@typing.final
class SearchAttributes(google.protobuf.message.Message):
    """A user-defined set of *indexed* fields that are used/exposed when listing/searching workflows.
    The payload is not serialized in a user-defined way.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class IndexedFieldsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> Global___Payload: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: Global___Payload | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing.Literal["value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    INDEXED_FIELDS_FIELD_NUMBER: builtins.int
    @property
    def indexed_fields(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[
        builtins.str, Global___Payload
    ]: ...
    def __init__(
        self,
        *,
        indexed_fields: collections.abc.Mapping[builtins.str, Global___Payload]
        | None = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["indexed_fields", b"indexed_fields"]
    ) -> None: ...

Global___SearchAttributes: typing_extensions.TypeAlias = SearchAttributes

@typing.final
class Memo(google.protobuf.message.Message):
    """A user-defined set of *unindexed* fields that are exposed when listing/searching workflows"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class FieldsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> Global___Payload: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: Global___Payload | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing.Literal["value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    FIELDS_FIELD_NUMBER: builtins.int
    @property
    def fields(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[
        builtins.str, Global___Payload
    ]: ...
    def __init__(
        self,
        *,
        fields: collections.abc.Mapping[builtins.str, Global___Payload] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["fields", b"fields"]) -> None: ...

Global___Memo: typing_extensions.TypeAlias = Memo

@typing.final
class Header(google.protobuf.message.Message):
    """Contains metadata that can be attached to a variety of requests, like starting a workflow, and
    can be propagated between, for example, workflows and activities.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class FieldsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> Global___Payload: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: Global___Payload | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing.Literal["value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    FIELDS_FIELD_NUMBER: builtins.int
    @property
    def fields(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[
        builtins.str, Global___Payload
    ]: ...
    def __init__(
        self,
        *,
        fields: collections.abc.Mapping[builtins.str, Global___Payload] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["fields", b"fields"]) -> None: ...

Global___Header: typing_extensions.TypeAlias = Header

@typing.final
class WorkflowExecution(google.protobuf.message.Message):
    """Identifies a specific workflow within a namespace. Practically speaking, because run_id is a
    uuid, a workflow execution is globally unique. Note that many commands allow specifying an empty
    run id as a way of saying "target the latest run of the workflow".
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WORKFLOW_ID_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    workflow_id: builtins.str
    run_id: builtins.str
    def __init__(
        self,
        *,
        workflow_id: builtins.str = ...,
        run_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal["run_id", b"run_id", "workflow_id", b"workflow_id"],
    ) -> None: ...

Global___WorkflowExecution: typing_extensions.TypeAlias = WorkflowExecution

@typing.final
class WorkflowType(google.protobuf.message.Message):
    """Represents the identifier used by a workflow author to define the workflow. Typically, the
    name of a function. This is sometimes referred to as the workflow's "name"
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

Global___WorkflowType: typing_extensions.TypeAlias = WorkflowType

@typing.final
class ActivityType(google.protobuf.message.Message):
    """Represents the identifier used by a activity author to define the activity. Typically, the
    name of a function. This is sometimes referred to as the activity's "name"
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

Global___ActivityType: typing_extensions.TypeAlias = ActivityType

@typing.final
class RetryPolicy(google.protobuf.message.Message):
    """How retries ought to be handled, usable by both workflows and activities"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INITIAL_INTERVAL_FIELD_NUMBER: builtins.int
    BACKOFF_COEFFICIENT_FIELD_NUMBER: builtins.int
    MAXIMUM_INTERVAL_FIELD_NUMBER: builtins.int
    MAXIMUM_ATTEMPTS_FIELD_NUMBER: builtins.int
    NON_RETRYABLE_ERROR_TYPES_FIELD_NUMBER: builtins.int
    backoff_coefficient: builtins.float
    """Coefficient used to calculate the next retry interval.
    The next retry interval is previous interval multiplied by the coefficient.
    Must be 1 or larger.
    """
    maximum_attempts: builtins.int
    """Maximum number of attempts. When exceeded the retries stop even if not expired yet.
    1 disables retries. 0 means unlimited (up to the timeouts)
    """
    @property
    def initial_interval(self) -> google.protobuf.duration_pb2.Duration:
        """Interval of the first retry. If retryBackoffCoefficient is 1.0 then it is used for all retries."""

    @property
    def maximum_interval(self) -> google.protobuf.duration_pb2.Duration:
        """Maximum interval between retries. Exponential backoff leads to interval increase.
        This value is the cap of the increase. Default is 100x of the initial interval.
        """

    @property
    def non_retryable_error_types(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Non-Retryable errors types. Will stop retrying if the error type matches this list. Note that
        this is not a substring match, the error *type* (not message) must match exactly.
        """

    def __init__(
        self,
        *,
        initial_interval: google.protobuf.duration_pb2.Duration | None = ...,
        backoff_coefficient: builtins.float = ...,
        maximum_interval: google.protobuf.duration_pb2.Duration | None = ...,
        maximum_attempts: builtins.int = ...,
        non_retryable_error_types: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "initial_interval",
            b"initial_interval",
            "maximum_interval",
            b"maximum_interval",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "backoff_coefficient",
            b"backoff_coefficient",
            "initial_interval",
            b"initial_interval",
            "maximum_attempts",
            b"maximum_attempts",
            "maximum_interval",
            b"maximum_interval",
            "non_retryable_error_types",
            b"non_retryable_error_types",
        ],
    ) -> None: ...

Global___RetryPolicy: typing_extensions.TypeAlias = RetryPolicy

@typing.final
class MeteringMetadata(google.protobuf.message.Message):
    """Metadata relevant for metering purposes"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NONFIRST_LOCAL_ACTIVITY_EXECUTION_ATTEMPTS_FIELD_NUMBER: builtins.int
    nonfirst_local_activity_execution_attempts: builtins.int
    """Count of local activities which have begun an execution attempt during this workflow task,
    and whose first attempt occurred in some previous task. This is used for metering
    purposes, and does not affect workflow state.

    (-- api-linter: core::0141::forbidden-types=disabled
        aip.dev/not-precedent: Negative values make no sense to represent. --)
    """
    def __init__(
        self,
        *,
        nonfirst_local_activity_execution_attempts: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "nonfirst_local_activity_execution_attempts",
            b"nonfirst_local_activity_execution_attempts",
        ],
    ) -> None: ...

Global___MeteringMetadata: typing_extensions.TypeAlias = MeteringMetadata

@typing.final
class WorkerVersionStamp(google.protobuf.message.Message):
    """Deprecated. This message is replaced with `Deployment` and `VersioningBehavior`.
    Identifies the version(s) of a worker that processed a task
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUILD_ID_FIELD_NUMBER: builtins.int
    USE_VERSIONING_FIELD_NUMBER: builtins.int
    build_id: builtins.str
    """An opaque whole-worker identifier. Replaces the deprecated `binary_checksum` field when this
    message is included in requests which previously used that.
    """
    use_versioning: builtins.bool
    """If set, the worker is opting in to worker versioning. Otherwise, this is used only as a
    marker for workflow reset points and the BuildIDs search attribute.
    """
    def __init__(
        self,
        *,
        build_id: builtins.str = ...,
        use_versioning: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "build_id", b"build_id", "use_versioning", b"use_versioning"
        ],
    ) -> None: ...

Global___WorkerVersionStamp: typing_extensions.TypeAlias = WorkerVersionStamp

@typing.final
class WorkerVersionCapabilities(google.protobuf.message.Message):
    """Identifies the version that a worker is compatible with when polling or identifying itself,
    and whether or not this worker is opting into the build-id based versioning feature. This is
    used by matching to determine which workers ought to receive what tasks.
    Deprecated. Use WorkerDeploymentOptions instead.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BUILD_ID_FIELD_NUMBER: builtins.int
    USE_VERSIONING_FIELD_NUMBER: builtins.int
    DEPLOYMENT_SERIES_NAME_FIELD_NUMBER: builtins.int
    build_id: builtins.str
    """An opaque whole-worker identifier"""
    use_versioning: builtins.bool
    """If set, the worker is opting in to worker versioning, and wishes to only receive appropriate
    tasks.
    """
    deployment_series_name: builtins.str
    """Must be sent if user has set a deployment series name (versioning-3)."""
    def __init__(
        self,
        *,
        build_id: builtins.str = ...,
        use_versioning: builtins.bool = ...,
        deployment_series_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "build_id",
            b"build_id",
            "deployment_series_name",
            b"deployment_series_name",
            "use_versioning",
            b"use_versioning",
        ],
    ) -> None: ...

Global___WorkerVersionCapabilities: typing_extensions.TypeAlias = (
    WorkerVersionCapabilities
)

@typing.final
class ResetOptions(google.protobuf.message.Message):
    """Describes where and how to reset a workflow, used for batch reset currently
    and may be used for single-workflow reset later.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FIRST_WORKFLOW_TASK_FIELD_NUMBER: builtins.int
    LAST_WORKFLOW_TASK_FIELD_NUMBER: builtins.int
    WORKFLOW_TASK_ID_FIELD_NUMBER: builtins.int
    BUILD_ID_FIELD_NUMBER: builtins.int
    RESET_REAPPLY_TYPE_FIELD_NUMBER: builtins.int
    CURRENT_RUN_ONLY_FIELD_NUMBER: builtins.int
    RESET_REAPPLY_EXCLUDE_TYPES_FIELD_NUMBER: builtins.int
    workflow_task_id: builtins.int
    """The id of a specific `WORKFLOW_TASK_COMPLETED`,`WORKFLOW_TASK_TIMED_OUT`, `WORKFLOW_TASK_FAILED`, or
    `WORKFLOW_TASK_STARTED` event to reset to.
    Note that this option doesn't make sense when used as part of a batch request.
    """
    build_id: builtins.str
    """Resets to the first workflow task processed by this build id.
    If the workflow was not processed by the build id, or the workflow task can't be
    determined, no reset will be performed.
    Note that by default, this reset is allowed to be to a prior run in a chain of
    continue-as-new.
    """
    reset_reapply_type: temporalio.api.enums.v1.reset_pb2.ResetReapplyType.ValueType
    """Deprecated. Use `options`.
    Default: RESET_REAPPLY_TYPE_SIGNAL
    """
    current_run_only: builtins.bool
    """If true, limit the reset to only within the current run. (Applies to build_id targets and
    possibly others in the future.)
    """
    @property
    def first_workflow_task(self) -> google.protobuf.empty_pb2.Empty:
        """Resets to the first workflow task completed or started event."""

    @property
    def last_workflow_task(self) -> google.protobuf.empty_pb2.Empty:
        """Resets to the last workflow task completed or started event."""

    @property
    def reset_reapply_exclude_types(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        temporalio.api.enums.v1.reset_pb2.ResetReapplyExcludeType.ValueType
    ]:
        """Event types not to be reapplied"""

    def __init__(
        self,
        *,
        first_workflow_task: google.protobuf.empty_pb2.Empty | None = ...,
        last_workflow_task: google.protobuf.empty_pb2.Empty | None = ...,
        workflow_task_id: builtins.int = ...,
        build_id: builtins.str = ...,
        reset_reapply_type: temporalio.api.enums.v1.reset_pb2.ResetReapplyType.ValueType = ...,
        current_run_only: builtins.bool = ...,
        reset_reapply_exclude_types: collections.abc.Iterable[
            temporalio.api.enums.v1.reset_pb2.ResetReapplyExcludeType.ValueType
        ]
        | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "build_id",
            b"build_id",
            "first_workflow_task",
            b"first_workflow_task",
            "last_workflow_task",
            b"last_workflow_task",
            "target",
            b"target",
            "workflow_task_id",
            b"workflow_task_id",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "build_id",
            b"build_id",
            "current_run_only",
            b"current_run_only",
            "first_workflow_task",
            b"first_workflow_task",
            "last_workflow_task",
            b"last_workflow_task",
            "reset_reapply_exclude_types",
            b"reset_reapply_exclude_types",
            "reset_reapply_type",
            b"reset_reapply_type",
            "target",
            b"target",
            "workflow_task_id",
            b"workflow_task_id",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["target", b"target"]
    ) -> (
        typing.Literal[
            "first_workflow_task", "last_workflow_task", "workflow_task_id", "build_id"
        ]
        | None
    ): ...

Global___ResetOptions: typing_extensions.TypeAlias = ResetOptions

@typing.final
class Callback(google.protobuf.message.Message):
    """Callback to attach to various events in the system, e.g. workflow run completion."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Nexus(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class HeaderEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            value: builtins.str
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: builtins.str = ...,
            ) -> None: ...
            def ClearField(
                self, field_name: typing.Literal["key", b"key", "value", b"value"]
            ) -> None: ...

        URL_FIELD_NUMBER: builtins.int
        HEADER_FIELD_NUMBER: builtins.int
        url: builtins.str
        """Callback URL."""
        @property
        def header(
            self,
        ) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
            """Header to attach to callback request."""

        def __init__(
            self,
            *,
            url: builtins.str = ...,
            header: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        ) -> None: ...
        def ClearField(
            self, field_name: typing.Literal["header", b"header", "url", b"url"]
        ) -> None: ...

    @typing.final
    class Internal(google.protobuf.message.Message):
        """Callbacks to be delivered internally within the system.
        This variant is not settable in the API and will be rejected by the service with an INVALID_ARGUMENT error.
        The only reason that this is exposed is because callbacks are replicated across clusters via the
        WorkflowExecutionStarted event, which is defined in the public API.
        """

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        DATA_FIELD_NUMBER: builtins.int
        data: builtins.bytes
        """Opaque internal data."""
        def __init__(
            self,
            *,
            data: builtins.bytes = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["data", b"data"]) -> None: ...

    NEXUS_FIELD_NUMBER: builtins.int
    INTERNAL_FIELD_NUMBER: builtins.int
    LINKS_FIELD_NUMBER: builtins.int
    @property
    def nexus(self) -> Global___Callback.Nexus: ...
    @property
    def internal(self) -> Global___Callback.Internal: ...
    @property
    def links(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___Link
    ]:
        """Links associated with the callback. It can be used to link to underlying resources of the
        callback.
        """

    def __init__(
        self,
        *,
        nexus: Global___Callback.Nexus | None = ...,
        internal: Global___Callback.Internal | None = ...,
        links: collections.abc.Iterable[Global___Link] | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "internal", b"internal", "nexus", b"nexus", "variant", b"variant"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "internal",
            b"internal",
            "links",
            b"links",
            "nexus",
            b"nexus",
            "variant",
            b"variant",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["variant", b"variant"]
    ) -> typing.Literal["nexus", "internal"] | None: ...

Global___Callback: typing_extensions.TypeAlias = Callback

@typing.final
class Link(google.protobuf.message.Message):
    """Link can be associated with history events. It might contain information about an external entity
    related to the history event. For example, workflow A makes a Nexus call that starts workflow B:
    in this case, a history event in workflow A could contain a Link to the workflow started event in
    workflow B, and vice-versa.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class WorkflowEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class EventReference(google.protobuf.message.Message):
            """EventReference is a direct reference to a history event through the event ID."""

            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            EVENT_ID_FIELD_NUMBER: builtins.int
            EVENT_TYPE_FIELD_NUMBER: builtins.int
            event_id: builtins.int
            event_type: temporalio.api.enums.v1.event_type_pb2.EventType.ValueType
            def __init__(
                self,
                *,
                event_id: builtins.int = ...,
                event_type: temporalio.api.enums.v1.event_type_pb2.EventType.ValueType = ...,
            ) -> None: ...
            def ClearField(
                self,
                field_name: typing.Literal[
                    "event_id", b"event_id", "event_type", b"event_type"
                ],
            ) -> None: ...

        @typing.final
        class RequestIdReference(google.protobuf.message.Message):
            """RequestIdReference is a indirect reference to a history event through the request ID."""

            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            REQUEST_ID_FIELD_NUMBER: builtins.int
            EVENT_TYPE_FIELD_NUMBER: builtins.int
            request_id: builtins.str
            event_type: temporalio.api.enums.v1.event_type_pb2.EventType.ValueType
            def __init__(
                self,
                *,
                request_id: builtins.str = ...,
                event_type: temporalio.api.enums.v1.event_type_pb2.EventType.ValueType = ...,
            ) -> None: ...
            def ClearField(
                self,
                field_name: typing.Literal[
                    "event_type", b"event_type", "request_id", b"request_id"
                ],
            ) -> None: ...

        NAMESPACE_FIELD_NUMBER: builtins.int
        WORKFLOW_ID_FIELD_NUMBER: builtins.int
        RUN_ID_FIELD_NUMBER: builtins.int
        EVENT_REF_FIELD_NUMBER: builtins.int
        REQUEST_ID_REF_FIELD_NUMBER: builtins.int
        namespace: builtins.str
        workflow_id: builtins.str
        run_id: builtins.str
        @property
        def event_ref(self) -> Global___Link.WorkflowEvent.EventReference: ...
        @property
        def request_id_ref(self) -> Global___Link.WorkflowEvent.RequestIdReference: ...
        def __init__(
            self,
            *,
            namespace: builtins.str = ...,
            workflow_id: builtins.str = ...,
            run_id: builtins.str = ...,
            event_ref: Global___Link.WorkflowEvent.EventReference | None = ...,
            request_id_ref: Global___Link.WorkflowEvent.RequestIdReference | None = ...,
        ) -> None: ...
        def HasField(
            self,
            field_name: typing.Literal[
                "event_ref",
                b"event_ref",
                "reference",
                b"reference",
                "request_id_ref",
                b"request_id_ref",
            ],
        ) -> builtins.bool: ...
        def ClearField(
            self,
            field_name: typing.Literal[
                "event_ref",
                b"event_ref",
                "namespace",
                b"namespace",
                "reference",
                b"reference",
                "request_id_ref",
                b"request_id_ref",
                "run_id",
                b"run_id",
                "workflow_id",
                b"workflow_id",
            ],
        ) -> None: ...
        def WhichOneof(
            self, oneof_group: typing.Literal["reference", b"reference"]
        ) -> typing.Literal["event_ref", "request_id_ref"] | None: ...

    @typing.final
    class BatchJob(google.protobuf.message.Message):
        """A link to a built-in batch job.
        Batch jobs can be used to perform operations on a set of workflows (e.g. terminate, signal, cancel, etc).
        This link can be put on workflow history events generated by actions taken by a batch job.
        """

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        JOB_ID_FIELD_NUMBER: builtins.int
        job_id: builtins.str
        def __init__(
            self,
            *,
            job_id: builtins.str = ...,
        ) -> None: ...
        def ClearField(
            self, field_name: typing.Literal["job_id", b"job_id"]
        ) -> None: ...

    @typing.final
    class Activity(google.protobuf.message.Message):
        """A link to an activity."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAMESPACE_FIELD_NUMBER: builtins.int
        ACTIVITY_ID_FIELD_NUMBER: builtins.int
        RUN_ID_FIELD_NUMBER: builtins.int
        namespace: builtins.str
        activity_id: builtins.str
        run_id: builtins.str
        def __init__(
            self,
            *,
            namespace: builtins.str = ...,
            activity_id: builtins.str = ...,
            run_id: builtins.str = ...,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing.Literal[
                "activity_id",
                b"activity_id",
                "namespace",
                b"namespace",
                "run_id",
                b"run_id",
            ],
        ) -> None: ...

    @typing.final
    class NexusOperation(google.protobuf.message.Message):
        """A link to a standalone Nexus operation."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAMESPACE_FIELD_NUMBER: builtins.int
        OPERATION_ID_FIELD_NUMBER: builtins.int
        RUN_ID_FIELD_NUMBER: builtins.int
        namespace: builtins.str
        operation_id: builtins.str
        run_id: builtins.str
        def __init__(
            self,
            *,
            namespace: builtins.str = ...,
            operation_id: builtins.str = ...,
            run_id: builtins.str = ...,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing.Literal[
                "namespace",
                b"namespace",
                "operation_id",
                b"operation_id",
                "run_id",
                b"run_id",
            ],
        ) -> None: ...

    @typing.final
    class Workflow(google.protobuf.message.Message):
        """A link to a workflow execution. This is a more general version of WorkflowEvent that doesn't specify a
        particular event within the workflow, useful when you want to link to a workflow but there is no particular event to link to,
        such as a Query or a Rejected Update.
        """

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAMESPACE_FIELD_NUMBER: builtins.int
        WORKFLOW_ID_FIELD_NUMBER: builtins.int
        RUN_ID_FIELD_NUMBER: builtins.int
        REASON_FIELD_NUMBER: builtins.int
        namespace: builtins.str
        workflow_id: builtins.str
        run_id: builtins.str
        reason: builtins.str
        def __init__(
            self,
            *,
            namespace: builtins.str = ...,
            workflow_id: builtins.str = ...,
            run_id: builtins.str = ...,
            reason: builtins.str = ...,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing.Literal[
                "namespace",
                b"namespace",
                "reason",
                b"reason",
                "run_id",
                b"run_id",
                "workflow_id",
                b"workflow_id",
            ],
        ) -> None: ...

    WORKFLOW_EVENT_FIELD_NUMBER: builtins.int
    BATCH_JOB_FIELD_NUMBER: builtins.int
    ACTIVITY_FIELD_NUMBER: builtins.int
    NEXUS_OPERATION_FIELD_NUMBER: builtins.int
    WORKFLOW_FIELD_NUMBER: builtins.int
    @property
    def workflow_event(self) -> Global___Link.WorkflowEvent: ...
    @property
    def batch_job(self) -> Global___Link.BatchJob: ...
    @property
    def activity(self) -> Global___Link.Activity: ...
    @property
    def nexus_operation(self) -> Global___Link.NexusOperation: ...
    @property
    def workflow(self) -> Global___Link.Workflow: ...
    def __init__(
        self,
        *,
        workflow_event: Global___Link.WorkflowEvent | None = ...,
        batch_job: Global___Link.BatchJob | None = ...,
        activity: Global___Link.Activity | None = ...,
        nexus_operation: Global___Link.NexusOperation | None = ...,
        workflow: Global___Link.Workflow | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "activity",
            b"activity",
            "batch_job",
            b"batch_job",
            "nexus_operation",
            b"nexus_operation",
            "variant",
            b"variant",
            "workflow",
            b"workflow",
            "workflow_event",
            b"workflow_event",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "activity",
            b"activity",
            "batch_job",
            b"batch_job",
            "nexus_operation",
            b"nexus_operation",
            "variant",
            b"variant",
            "workflow",
            b"workflow",
            "workflow_event",
            b"workflow_event",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["variant", b"variant"]
    ) -> (
        typing.Literal[
            "workflow_event", "batch_job", "activity", "nexus_operation", "workflow"
        ]
        | None
    ): ...

Global___Link: typing_extensions.TypeAlias = Link

@typing.final
class Principal(google.protobuf.message.Message):
    """Principal is an authenticated caller identity computed by the server from trusted
    authentication context.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    type: builtins.str
    """Low-cardinality category of the principal (e.g., "jwt", "users")."""
    name: builtins.str
    """Identifier within that category (e.g., sub JWT claim, email address)."""
    def __init__(
        self,
        *,
        type: builtins.str = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["name", b"name", "type", b"type"]
    ) -> None: ...

Global___Principal: typing_extensions.TypeAlias = Principal

@typing.final
class Priority(google.protobuf.message.Message):
    """Priority contains metadata that controls relative ordering of task processing
    when tasks are backed up in a queue. Initially, Priority will be used in
    matching (workflow and activity) task queues. Later it may be used in history
    task queues and in rate limiting decisions.

    Priority is attached to workflows and activities. By default, activities
    inherit Priority from the workflow that created them, but may override fields
    when an activity is started or modified.

    Despite being named "Priority", this message also contains fields that
    control "fairness" mechanisms.

    For all fields, the field not present or equal to zero/empty string means to
    inherit the value from the calling workflow, or if there is no calling
    workflow, then use the default value.

    For all fields other than fairness_key, the zero value isn't meaningful so
    there's no confusion between inherit/default and a meaningful value. For
    fairness_key, the empty string will be interpreted as "inherit". This means
    that if a workflow has a non-empty fairness key, you can't override the
    fairness key of its activity to the empty string.

    The overall semantics of Priority are:
    1. First, consider "priority": higher priority (lower number) goes first.
    2. Then, consider fairness: try to dispatch tasks for different fairness keys
       in proportion to their weight.

    Applications may use any subset of mechanisms that are useful to them and
    leave the other fields to use default values.

    Not all queues in the system may support the "full" semantics of all priority
    fields. (Currently only support in matching task queues is planned.)
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRIORITY_KEY_FIELD_NUMBER: builtins.int
    FAIRNESS_KEY_FIELD_NUMBER: builtins.int
    FAIRNESS_WEIGHT_FIELD_NUMBER: builtins.int
    priority_key: builtins.int
    """Priority key is a positive integer from 1 to n, where smaller integers
    correspond to higher priorities (tasks run sooner). In general, tasks in
    a queue should be processed in close to priority order, although small
    deviations are possible.

    The maximum priority value (minimum priority) is determined by server
    configuration, and defaults to 5.

    If priority is not present (or zero), then the effective priority will be
    the default priority, which is calculated by (min+max)/2. With the
    default max of 5, and min of 1, that comes out to 3.
    """
    fairness_key: builtins.str
    """Fairness key is a short string that's used as a key for a fairness
    balancing mechanism. It may correspond to a tenant id, or to a fixed
    string like "high" or "low". The default is the empty string.

    The fairness mechanism attempts to dispatch tasks for a given key in
    proportion to its weight. For example, using a thousand distinct tenant
    ids, each with a weight of 1.0 (the default) will result in each tenant
    getting a roughly equal share of task dispatch throughput.

    (Note: this does not imply equal share of worker capacity! Fairness
    decisions are made based on queue statistics, not
    current worker load.)

    As another example, using keys "high" and "low" with weight 9.0 and 1.0
    respectively will prefer dispatching "high" tasks over "low" tasks at a
    9:1 ratio, while allowing either key to use all worker capacity if the
    other is not present.

    All fairness mechanisms, including rate limits, are best-effort and
    probabilistic. The results may not match what a "perfect" algorithm with
    infinite resources would produce. The more unique keys are used, the less
    accurate the results will be.

    Fairness keys are limited to 64 bytes.
    """
    fairness_weight: builtins.float
    """Fairness weight for a task can come from multiple sources for
    flexibility. From highest to lowest precedence:
    1. Weights for a small set of keys can be overridden in task queue
       configuration with an API.
    2. It can be attached to the workflow/activity in this field.
    3. The default weight of 1.0 will be used.

    Weight values are clamped to the range [0.001, 1000].
    """
    def __init__(
        self,
        *,
        priority_key: builtins.int = ...,
        fairness_key: builtins.str = ...,
        fairness_weight: builtins.float = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "fairness_key",
            b"fairness_key",
            "fairness_weight",
            b"fairness_weight",
            "priority_key",
            b"priority_key",
        ],
    ) -> None: ...

Global___Priority: typing_extensions.TypeAlias = Priority

@typing.final
class WorkerSelector(google.protobuf.message.Message):
    """This is used to send commands to a specific worker or a group of workers.
    Right now, it is used to send commands to a specific worker instance.
    Will be extended to be able to send command to multiple workers.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WORKER_INSTANCE_KEY_FIELD_NUMBER: builtins.int
    worker_instance_key: builtins.str
    """Worker instance key to which the command should be sent."""
    def __init__(
        self,
        *,
        worker_instance_key: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "selector", b"selector", "worker_instance_key", b"worker_instance_key"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "selector", b"selector", "worker_instance_key", b"worker_instance_key"
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["selector", b"selector"]
    ) -> typing.Literal["worker_instance_key"] | None: ...

Global___WorkerSelector: typing_extensions.TypeAlias = WorkerSelector

@typing.final
class OnConflictOptions(google.protobuf.message.Message):
    """When starting an execution with a conflict policy that uses an existing execution and there is already an existing
    running execution, OnConflictOptions defines actions to be taken on the existing running execution.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ATTACH_REQUEST_ID_FIELD_NUMBER: builtins.int
    ATTACH_COMPLETION_CALLBACKS_FIELD_NUMBER: builtins.int
    ATTACH_LINKS_FIELD_NUMBER: builtins.int
    attach_request_id: builtins.bool
    """Attaches the request ID to the running execution."""
    attach_completion_callbacks: builtins.bool
    """Attaches the completion callbacks to the running execution."""
    attach_links: builtins.bool
    """Attaches the links to the running execution."""
    def __init__(
        self,
        *,
        attach_request_id: builtins.bool = ...,
        attach_completion_callbacks: builtins.bool = ...,
        attach_links: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "attach_completion_callbacks",
            b"attach_completion_callbacks",
            "attach_links",
            b"attach_links",
            "attach_request_id",
            b"attach_request_id",
        ],
    ) -> None: ...

Global___OnConflictOptions: typing_extensions.TypeAlias = OnConflictOptions

@typing.final
class TimeSkippingConfig(google.protobuf.message.Message):
    """The configuration for time skipping of a workflow execution (a chain of runs including retries, cron, continue-as-new).
    When time skipping is enabled, virtual time advances automatically whenever there is no in-flight work.
    In-flight work includes activities, child workflows, Nexus operations, signal/cancel external workflow operations,
    and possibly other features added in the future.
    User timers are not classified as in-flight work and will be skipped over; the virtual clock may also skip to the
    time point of the registered fast forward when there is no in-flight work.
    When time is skipped, a WorkflowExecutionTimeSkippingTransitionedEvent will be
    added to the workflow history to capture the state changes.

    For child workflows, by default, if the parent execution is skipping time, the child execution will also skip time,
    but a parent's fast_forward won't affect its child's execution. A flag is provided to disable propagation of the
    "enabled" flag to child workflows; regardless of that flag, a child workflow inherits the virtual time from the
    parent execution as its start time.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENABLED_FIELD_NUMBER: builtins.int
    FAST_FORWARD_FIELD_NUMBER: builtins.int
    DISABLE_CHILD_PROPAGATION_FIELD_NUMBER: builtins.int
    enabled: builtins.bool
    """Enables or disables time skipping for this workflow execution."""
    disable_child_propagation: builtins.bool
    """By default, child workflows inherit the "enabled" flag when they are started.
    This flag disables that inheritance.
    """
    @property
    def fast_forward(self) -> google.protobuf.duration_pb2.Duration:
        """Optionally fast-forward the current workflow execution by this duration ahead of current workflow execution time.
        After the fast-forward completes, time skipping is disabled, and this
        action is recorded in the WorkflowExecutionTimeSkippingTransitionedEvent. It can be re-enabled by
        setting `enabled` to true or setting `fast_forward` again via UpdateWorkflowExecutionOptions.
        The current workflow execution is a chain of runs (retries, cron, continue-as-new);
        child workflows are separate executions, so this fast_forward won't affect them.

        For a given workflow execution, only one active fast-forward is allowed at a time.
        If a new fast-forward is set via UpdateWorkflowExecutionOptions before the previous
        one completes, the new one will override the previous one.
        If the fast-forward duration exceeds the remaining execution timeout, time will only
        be fast-forwarded up to the end of the execution.
        """

    def __init__(
        self,
        *,
        enabled: builtins.bool = ...,
        fast_forward: google.protobuf.duration_pb2.Duration | None = ...,
        disable_child_propagation: builtins.bool = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["fast_forward", b"fast_forward"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "disable_child_propagation",
            b"disable_child_propagation",
            "enabled",
            b"enabled",
            "fast_forward",
            b"fast_forward",
        ],
    ) -> None: ...

Global___TimeSkippingConfig: typing_extensions.TypeAlias = TimeSkippingConfig

@typing.final
class TimeSkippingStatePropagation(google.protobuf.message.Message):
    """The time-skipping state that needs to be propagated from a parent workflow to a child workflow,
    or through a chain of runs.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INITIAL_SKIPPED_DURATION_FIELD_NUMBER: builtins.int
    FAST_FORWARD_TARGET_TIME_FIELD_NUMBER: builtins.int
    @property
    def initial_skipped_duration(self) -> google.protobuf.duration_pb2.Duration:
        """The time skipped by the previous execution that started this workflow.
        It can happen in child workflows and a chain of runs (CaN, cron, retry).
        """

    @property
    def fast_forward_target_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """If there is a fast-forward action set for the previous run in a chain of runs,
        the target time should be propagated to the next run as well.
        """

    def __init__(
        self,
        *,
        initial_skipped_duration: google.protobuf.duration_pb2.Duration | None = ...,
        fast_forward_target_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "fast_forward_target_time",
            b"fast_forward_target_time",
            "initial_skipped_duration",
            b"initial_skipped_duration",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "fast_forward_target_time",
            b"fast_forward_target_time",
            "initial_skipped_duration",
            b"initial_skipped_duration",
        ],
    ) -> None: ...

Global___TimeSkippingStatePropagation: typing_extensions.TypeAlias = (
    TimeSkippingStatePropagation
)
