# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temporal/api/testservice/v1/request_response.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    "",
    "temporal/api/testservice/v1/request_response.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n2temporal/api/testservice/v1/request_response.proto\x12\x1btemporal.api.testservice.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\x19\n\x17LockTimeSkippingRequest"\x1a\n\x18LockTimeSkippingResponse"\x1b\n\x19UnlockTimeSkippingRequest"\x1c\n\x1aUnlockTimeSkippingResponse"B\n\x11SleepUntilRequest\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp";\n\x0cSleepRequest\x12+\n\x08\x64uration\x18\x01 \x01(\x0b\x32\x19.google.protobuf.Duration"\x0f\n\rSleepResponse"B\n\x16GetCurrentTimeResponse\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\xaa\x01\n\x1eio.temporal.api.testservice.v1B\x14RequestResponseProtoP\x01Z-go.temporal.io/api/testservice/v1;testservice\xaa\x02\x1dTemporalio.Api.TestService.V1\xea\x02 Temporalio::Api::TestService::V1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "temporal.api.testservice.v1.request_response_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n\036io.temporal.api.testservice.v1B\024RequestResponseProtoP\001Z-go.temporal.io/api/testservice/v1;testservice\252\002\035Temporalio.Api.TestService.V1\352\002 Temporalio::Api::TestService::V1"
    _globals["_LOCKTIMESKIPPINGREQUEST"]._serialized_start = 148
    _globals["_LOCKTIMESKIPPINGREQUEST"]._serialized_end = 173
    _globals["_LOCKTIMESKIPPINGRESPONSE"]._serialized_start = 175
    _globals["_LOCKTIMESKIPPINGRESPONSE"]._serialized_end = 201
    _globals["_UNLOCKTIMESKIPPINGREQUEST"]._serialized_start = 203
    _globals["_UNLOCKTIMESKIPPINGREQUEST"]._serialized_end = 230
    _globals["_UNLOCKTIMESKIPPINGRESPONSE"]._serialized_start = 232
    _globals["_UNLOCKTIMESKIPPINGRESPONSE"]._serialized_end = 260
    _globals["_SLEEPUNTILREQUEST"]._serialized_start = 262
    _globals["_SLEEPUNTILREQUEST"]._serialized_end = 328
    _globals["_SLEEPREQUEST"]._serialized_start = 330
    _globals["_SLEEPREQUEST"]._serialized_end = 389
    _globals["_SLEEPRESPONSE"]._serialized_start = 391
    _globals["_SLEEPRESPONSE"]._serialized_end = 406
    _globals["_GETCURRENTTIMERESPONSE"]._serialized_start = 408
    _globals["_GETCURRENTTIMERESPONSE"]._serialized_end = 474
# @@protoc_insertion_point(module_scope)
