# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporal/api/enums/v1/id.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1etemporal/api/enums/v1/id.proto\x12\x15temporal.api.enums.v1*\xac\x01\n\rIdReusePolicy\x12\x1f\n\x1bID_REUSE_POLICY_UNSPECIFIED\x10\x00\x12#\n\x1fID_REUSE_POLICY_ALLOW_DUPLICATE\x10\x01\x12/\n+ID_REUSE_POLICY_ALLOW_DUPLICATE_FAILED_ONLY\x10\x02\x12$\n ID_REUSE_POLICY_REJECT_DUPLICATE\x10\x03*\xa3\x01\n\x10IdConflictPolicy\x12"\n\x1eID_CONFLICT_POLICY_UNSPECIFIED\x10\x00\x12\x1b\n\x17ID_CONFLICT_POLICY_FAIL\x10\x01\x12#\n\x1fID_CONFLICT_POLICY_USE_EXISTING\x10\x02\x12)\n%ID_CONFLICT_POLICY_TERMINATE_EXISTING\x10\x03\x42\x7f\n\x18io.temporal.api.enums.v1B\x07IdProtoP\x01Z!go.temporal.io/api/enums/v1;enums\xaa\x02\x17Temporalio.Api.Enums.V1\xea\x02\x1aTemporalio::Api::Enums::V1b\x06proto3'
)

_IDREUSEPOLICY = DESCRIPTOR.enum_types_by_name["IdReusePolicy"]
IdReusePolicy = enum_type_wrapper.EnumTypeWrapper(_IDREUSEPOLICY)
_IDCONFLICTPOLICY = DESCRIPTOR.enum_types_by_name["IdConflictPolicy"]
IdConflictPolicy = enum_type_wrapper.EnumTypeWrapper(_IDCONFLICTPOLICY)
ID_REUSE_POLICY_UNSPECIFIED = 0
ID_REUSE_POLICY_ALLOW_DUPLICATE = 1
ID_REUSE_POLICY_ALLOW_DUPLICATE_FAILED_ONLY = 2
ID_REUSE_POLICY_REJECT_DUPLICATE = 3
ID_CONFLICT_POLICY_UNSPECIFIED = 0
ID_CONFLICT_POLICY_FAIL = 1
ID_CONFLICT_POLICY_USE_EXISTING = 2
ID_CONFLICT_POLICY_TERMINATE_EXISTING = 3


if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\030io.temporal.api.enums.v1B\007IdProtoP\001Z!go.temporal.io/api/enums/v1;enums\252\002\027Temporalio.Api.Enums.V1\352\002\032Temporalio::Api::Enums::V1"
    _IDREUSEPOLICY._serialized_start = 58
    _IDREUSEPOLICY._serialized_end = 230
    _IDCONFLICTPOLICY._serialized_start = 233
    _IDCONFLICTPOLICY._serialized_end = 396
# @@protoc_insertion_point(module_scope)
