# Generated by nex-gen. DO NOT EDIT!

from __future__ import annotations

from . import service as _service
from .operations.signal_with_start_workflow import signal_with_start_workflow

__all__ = [
    "signal_with_start_workflow",
]


__nexus_operation_registry__ = {
    (
        "WorkflowService",
        "SignalWithStartWorkflowExecution",
    ): _service.WorkflowService.signal_with_start_workflow,
}
