name: Build Binaries
on:
  push:
    branches:
      - main
      - "releases/*"
      - build_binaries_otel
permissions:
  contents: read

jobs:
  # Compile the binaries and upload artifacts
  compile-binaries:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            package-suffix: linux-amd64
          - os: ubuntu-arm
            package-suffix: linux-aarch64
            runsOn: ubuntu-24.04-arm64-2-core
          - os: macos-intel
            package-suffix: macos-amd64
            runsOn: macos-15-intel
          - os: macos-arm
            package-suffix: macos-aarch64
            runsOn: macos-14
          - os: windows-latest
            package-suffix: windows-amd64
    runs-on: ${{ matrix.runsOn || matrix.os }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          submodules: recursive
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.14"

      # Install Rust locally for non-Linux (Linux uses an internal docker
      # command to build with cibuildwheel which uses rustup install defined
      # in pyproject.toml)
      - if: ${{ runner.os != 'Linux' }}
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
      - if: ${{ runner.os != 'Linux' }}
        uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae # v2
        with:
          workspaces: temporalio/bridge -> target
      - uses: astral-sh/setup-uv@e58605a9b6da7c637471fab8847a5e5a6b8df081 # v5
      - run: uv sync --all-extras

      # Add the source dist only for Linux x64 for now
      - if: ${{ matrix.package-suffix == 'linux-amd64' }}
        run: uv build --sdist

      # Build the wheel
      - run: uv run cibuildwheel --output-dir dist

      # Install the wheel in a new venv and run a test
      - name: Test wheel
        shell: bash
        run: |
          mkdir __test_wheel__
          cd __test_wheel__
          cp -r ../tests .
          python -m venv .venv
          bindir=bin
          if [ "$RUNNER_OS" = "Windows" ]; then
            bindir=Scripts
          fi
          ./.venv/$bindir/pip install pytest pytest_asyncio grpcio pydantic opentelemetry-api opentelemetry-sdk
          ./.venv/$bindir/pip install --prefer-binary ../dist/*.whl
          ./.venv/$bindir/python -m pytest -s tests/worker/test_workflow.py -k test_workflow_hello

      # Upload dist
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: packages-${{ matrix.package-suffix }}
          path: dist
